### ISSUE TITLE
run with function_graph result in "The CPU has been disabled by the guest operating system"

### ISSUE THREAD

**Issue by lcytxw** [rostedt/trace-cmd#10]
Hi, everyone:
I have a strange problem. When I run 'sudo trace-cmd record -p function_graph -P xxx' I got the following error.
"The CPU has been disabled by the guest operating system. Power off or reset the vitural machine"
I tryed many times and the error still occur. The following is the specific information.
`---------------------------------------------------------------------`
VMWare Workstation: 15.0.2 build-10952284
Host Machine: Ubuntu 18.04
Kernel Version: Linux ubuntu 4.15.0-50-generic

CPU Information:
processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
`---------------------------------------------------------------------`

**Comment by rostedt** [comment]
Please report issues at: https://bugzilla.kernel.org/buglist.cgi?component=Trace-cmd%2FKernelshark&list_id=1026531&product=Tools&resolution=---
