### ISSUE TITLE
Automatically synchronize github.com repository with kernel.org repository

### ISSUE THREAD

**Issue by wschlich** [rostedt/trace-cmd#2]
Hi Steven!

It seems that active delopment is happening here:
https://git.kernel.org/cgit/linux/kernel/git/rostedt/trace-cmd.git

Can you setup an automatic synchronization between your kernel.org repository and your github.com repository, so we can make use of the github notifications etc.?

Cheers,
Wolfram

**Comment by mpe** [comment]
Or just delete this repo as it's confusing people.
