### ISSUE TITLE
How to get the right function list from trace-cmd recording

### ISSUE THREAD

**Issue by mudongliang** [rostedt/trace-cmd#9]
I recorded all the kernel functions with `trace-cmd record -p function -c ./test_script`.

But when I try to report the executed kernel functions in the recording, I found the function I want is not in the result of `trace-cmd report` or `trace-cmd report -F "function"`, however, it exists in the `trace-cmd report -f`. Although `trace-cmd report -f` shows the executed function list, but the sequence is incorrect. What I want is the function list with the execution order at runtime.

In order to make it clear, I attached one example in my side,
```sh
root@syzkaller:~# trace-cmd --version
trace-cmd version 2.8.dev
```
for `loopback_net_init`, it is not in the result(`trace-cmd report`) or result-F(`trace-cmd report -F "function"`), but it is in the result-f(`trace-cmd report -f).
The trace.dat is uploaded as [trace.zip](https://github.com/rostedt/trace-cmd/files/3245342/trace.zip)

**Comment by rostedt** [comment]
Note, this repo is a mirror of the real repo and is not monitored. Someone happened to tell me about this issue. It's best to file issues on bugzilla.kernel.org.

Anyway, do you see it if you add "-O parent"? trace-cmd report -O parent

**Comment by mudongliang** [comment]
OK, let's close it. And I will report to kernel bugzilla
